# Generated by Django 5.1.2 on 2024-10-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventSponser',
        ),
    ]
